from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os

def generate_pdf_report(filename, user_email, insights, plot_path=None):
    try:
        doc = SimpleDocTemplate(filename, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []
        
        title = Paragraph("🤖 Data Scientist Agent - Analysis Report", styles['Heading1'])
        story.append(title)
        story.append(Spacer(1, 12))
        
        client_info = Paragraph(f"<b>Client Email:</b> {user_email}", styles['Normal'])
        story.append(client_info)
        story.append(Spacer(1, 12))
        
        date_info = Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal'])
        story.append(date_info)
        story.append(Spacer(1, 12))
        
        story.append(Paragraph("<b>Key Insights:</b>", styles['Heading2']))
        for line in insights.split('\n'):
            if line.strip():
                story.append(Paragraph(f"• {line}", styles['Normal']))
        story.append(Spacer(1, 12))
        
        if plot_path and os.path.exists(plot_path):
            story.append(Paragraph("<b>Visualization:</b>", styles['Heading2']))
            img = Image(plot_path, width=400, height=300)
            story.append(img)
        
        story.append(Spacer(1, 20))
        footer = Paragraph("<i>Generated by Data Scientist Agent v1.4</i>", styles['Italic'])
        story.append(footer)
        
        doc.build(story)
        return True
    except Exception as e:
        print(f"❌ PDF Generation Error: {e}")
        return False
